# Generated by Django 5.1.5 on 2025-12-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0014_alter_audiotranscription_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Airline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("icao_code", models.CharField(blank=True, max_length=3, null=True)),
                ("iata_code", models.CharField(blank=True, max_length=2, null=True)),
                ("callsign", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TranscriptionCorrection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "incorrect_text",
                    models.CharField(
                        help_text="Texto incorrecto (en minúsculas)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "correct_text",
                    models.CharField(help_text="Texto corregido", max_length=100),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("airline", "Aerolínea"),
                            ("number", "Número"),
                            ("terminology", "Terminología Aeronáutica"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
