# Generated by Django 5.1.5 on 2025-12-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transcriptiongroup",
            name="airport_code",
            field=models.CharField(
                blank=True,
                help_text="Código ICAO del aeropuerto (ej: LECU)",
                max_length=10,
                null=True,
            ),
        ),
    ]
