"""
Django settings for transcriptionAPI project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from datetime import timedelta
from dotenv import load_dotenv
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')

CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL','amqp://guest:guest@localhost//')
OLLAMA_MODEL = os.getenv('OLLAMA_MODEL', 'phi4')

"""CELERY_QUEUES = {
    'auth_queue': {
        'exchange': 'auth_queue',  # exchange para auth_queue
        'exchange_type': 'direct', # Asegúrate de que el tipo sea 'direct'
        'binding_key': 'auth_key', # La clave de enrutamiento
    },
}

# Enrutar las tareas a la cola auth_queue
CELERY_ROUTES = {
    'api.tasks.process_audio_task': {'queue': 'auth_queue'},
    'api.tasks.validate_conversation_task': {'queue': 'auth_queue'},
}"""

CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_BACKEND = 'django-db'

# --- CELERY ROBUSTNESS SETTINGS (VLAS v2.2.1) ---
# 1. Connection Stability: Evita errores al arrancar si RabbitMQ aun duerme
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

# 2. Data Safety: Solo confirmar la tarea cuando se termine (evita pérdida si crash)
CELERY_TASK_ACKS_LATE = True

# 3. Flow Control: Como usamos GPU, el worker solo debe tener 1 tarea en mano.
# Evita que acapare memoria y cause timeouts ("Indigestión").
CELERY_WORKER_PREFETCH_MULTIPLIER = 1

# 4. Time Limits: Evitar tareas zombies eternas
CELERY_TASK_TIME_LIMIT = 3600       # 1 hora hard limit (mata el proceso)
CELERY_TASK_SOFT_TIME_LIMIT = 3300  # 55 min soft limit (lanza excepción)

# 5. Heartbeats: Mantener conexión viva con RabbitMQ (evita "Connection Storm")
CELERY_BROKER_HEARTBEAT = 10 # Segundos


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', '0').lower() in ['true', 't', '1']

# Configuración de la URL del sitio
SITE_URL = os.getenv('SITE_URL', 'http://127.0.0.1:8000')


ALLOWED_HOSTS = ['*']

CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173', 
    'http://localhost:5174', 
    'http://172.16.32.85:5174', 
    'http://localhost:8080', 
    'http://127.0.0.1:8080',
    'http://192.168.11.102:8080',
    'http://80.27.4.120:8080',
]
# CORS_EXPOSE_HEADERS = ['content-disposition']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'django_celery_results',
    # Custom apps
    'api.apps.ApiConfig',
    # 'models.apps.ModelsConfig',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=10),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=5),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'transcriptionAPI.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'transcriptionAPI.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB', 'postgres'),  # Nombre de la base de datos
        'USER': os.getenv('POSTGRES_USER', 'postgres'),        # Usuario
        'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'postgres'),  # Contraseña
        'HOST': os.getenv('POSTGRES_HOST', 'postgres'),       # Host del servidor
        'PORT': os.getenv('POSTGRES_PORT', '5432'),           # Puerto
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-US'

TIME_ZONE = 'Europe/Madrid'

USE_I18N = True

USE_TZ = False

# Directorio para almacenar archivos subidos
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
